bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

letter/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='letter-index'),
    path('mail_letter/', views.mail_letter, name='mail-letter')
]

thai_food_superstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('letter-index/', include('letter.urls')),
    path('checkout/', include('checkout.urls')),
    path('recipes/', include('recipes.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letter/models.py
from django.db import models

# Create your models here.


class Subscribers(models.Model):

    class Meta: 
        verbose_name_plural = "Subscribers"

    email = models.EmailField(null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class MailMessage(models.Model):
    title = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)

    def __str__(self):
        return self.title

letter/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from . models import Subscribers, MailMessage
from django.contrib import messages
from django.core.mail import send_mail, EmailMessage
from django.db.models import Q
from django.db.models.functions import Lower
# Create your views here.
import pandas as pd


def index(request):
    if request.method == 'GET':
        allsubs = Subscribers.objects.all().count()
        newid = allsubs+1
        if 'subscribemail' in request.GET:
            # form = SubscibersForm(request.POST)
            subscrivers_new = Subscribers(newid, request.GET['subscribemail'])
            subscrivers_new.save()
            messages.success(request, 'Subscription Successful')
            return redirect('letter-index')

    context = {
        'Subscribers': Subscribers,
    }
    return render(request, 'letter/letter.html', context)


def mail_letter(request):
    # emails = Subscribers.objects.values('email')
    # query = None
    # queries = Q(email=query)
    # df = emails
    # read_frame(emails, fieldnames=['email'])
    emails = Subscribers.objects.all().count()
    # mail_list = Subscribers.email.values.tolist()
    # print(mail_list)
    if request.user.is_superuser:
        if request.method == 'GET':
            if emails > 0:
                df = pd.DataFrame(
                list(
                    Subscribers.objects.all().values(
                        "email"
                        )
                    )
                )
        # read_frame(emails, fieldnames=['email'])
                mail_list = df['email'].values.tolist()

                allMailMessage = MailMessage.objects.all().count()
                newid = allMailMessage + 1
        # form = MailMessageForm(request.POST)
                if 'titleletter' in request.GET:

                    title = request.GET['titleletter']
                    message = request.GET['messageletter']

                    message_new = MailMessage(newid, title, message)
                    message_new.save()

                    send_mail(title,
                    message,
                    'testsmtpmail@sns-autotransport.com',
                    mail_list)
                    messages.success(request, 'Message has been sent to the Mail List')
                    return redirect('mail-letter')
            else:
                messages.success(request, 'No Emails Found of newsletter where you send newsletter, First need to subscribe for newsletter')
    else:
        messages.success(request, 'This feature can use only superuser. Thank!')
    context = {
        'MailMessage': MailMessage,
    }
    return render(request, 'letter/mail_letter.html', context)

letter/templates/letter/index.html
{% extends 'partials/base.html' %}
{% block title %}Home Page {% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5 pt-5">
        <div class="col-md-4 offset-md-4">
            {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="card">
                <div class="card-body">
                    <h3>Subscribe to Newsletter</h3>
                    <hr>
                    <form method="GET" action="{% url 'letter-index' %}" >

                        <div id="div_id_email" class="form-group">
<label for="id_email" class=" requiredField">
                Email<span class="asteriskField">*</span>
</label>
<div>
<input type="email" required name="subscribemail" maxlength="254" class="emailinput form-control" required="" id="id_email">
</div> </div>

                        <input class="btn btn-info btn-block" type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

letter/templates/letter/letter.html
{% extends 'base.html' %}
{% block title %}Home Page {% endblock %}


{% block content %}
<div class="container" style="margin-top:200px;margin-bottom:50px;" >
    <div class="row mt-5 pt-5 pb-5">
        <div class="col-md-4 offset-md-4 text-center d-flex justify-conten-center">
            {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="card newsletter-container">
                <div class="card-body">
                    <h3>Subscribe to Newsletter</h3>
                    <hr>
                    <form method="GET" action="{% url 'letter-index' %}" >

                        <div id="div_id_email" class="form-group">
<label for="id_email" class=" requiredField">
                Email<span class="asteriskField">*</span>
</label>
<div>
<input type="email" required name="subscribemail" maxlength="254" class="emailinput form-control" required="" id="id_email">
</div> </div>

                        <input class="btn btn-info btn-block" type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

letter/templates/letter/mail_letter.html
{% extends 'base.html' %}
{% block title %}Mail Page {% endblock %}

{% block content %}
<div class="container" style="margin-top:200px;margin-bottom:50px;" >
    <div class="row mt-5 pt-5">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="card">
                <div class="card-body">
                    <form method="GET" action="{% url 'mail-letter' %}" >

                        <div id="div_id_title" class="form-group">
<label for="id_title" class=" requiredField">
                Title<span class="asteriskField">*</span>
</label>
<div>
<input type="text" required name="titleletter" maxlength="100" class="textinput form-control" required="" id="id_title">
</div> </div>
                    <div id="div_id_message" class="form-group">
<label for="id_message" class=" requiredField">
                Message<span class="asteriskField">*</span>
</label>
<div>
<textarea required name="messageletter" cols="40" rows="10" class="textarea form-control" required="" id="id_message"></textarea>
</div> </div>



                        <input class="btn btn-info btn-block" type="submit" value="Send Message">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}